version: '3.8'
services:

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    container_name: clean-phpmyadminserver
    environment:
      PMA_HOST: db
      PMA_USER: mysqlusername
      PMA_PASSWORD: mysqlpassword
    links:
      - db      
    ports:
      - "8081:80"

  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    container_name: clean-mysqldb

    environment:
      MYSQL_ROOT_PASSWORD: hardtohackpassword
      MYSQL_DATABASE: cleanwpdb
      MYSQL_USER: mysqlusername
      MYSQL_PASSWORD: mysqlpassword
    
    volumes:
      - db_data:/var/lib/mysql    


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: clean-wp
    volumes:
      ["./:/var/www/html"]   
    restart: always

    ports:
      - "8001:80"

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mysqlusername
      WORDPRESS_DB_PASSWORD: mysqlpassword
      WORDPRESS_DB_NAME: cleanwpdb

volumes:
  db_data:
    driver: local